apiVersion: v1
data:
  requirements.txt: |-
    grpcio
    grpcio-tools
    flask
    flask_cors
    datetime
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: frontend
  name: frontend-cm0
