apiVersion: v1
kind: Service
metadata:
    name: mongodb-lb
spec:
    type: LoadBalancer
    selector:
        io.kompose.service: mongodb
    ports:
        - name: mongodb
          protocol: TCP
          port: 27017 # Exposed port for external access.
          targetPort: 27017 # The port your MongoDB container listens on.
