apiVersion: v1
kind: Service
metadata:
    name: mongodb-external
spec:
    type: NodePort
    selector:
        io.kompose.service: mongodb
    ports:
        - name: mongodb
          protocol: TCP
          port: 27017 # The port that the service exposes internally.
          targetPort: 27017 # The port on which MongoDB is listening in the container.
          nodePort: 30017 # You can choose a specific port or leave it undefined (Kubernetes will assign one in the 30000-32767 range).
