apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: tournament-service
  name: tournament-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tournament-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: tournament-service
    spec:
      containers:
        - args:
            - bash
            - -c
            - pip install -r requirements.txt && python -u tournament_server.py
          image: python:3.12.9
          name: tournament-service
          ports:
            - containerPort: 50053
              protocol: TCP
          volumeMounts:
            - mountPath: /app/requirements.txt
              name: tournament-service-cm0
              subPath: requirements.txt
            - mountPath: /app/tournament_server.py
              name: tournament-service-cm1
              subPath: tournament_server.py
            - mountPath: /app/tournament_pb2_grpc.py
              name: tournament-service-cm2
              subPath: tournament_pb2_grpc.py
            - mountPath: /app/tournament_pb2.py
              name: tournament-service-cm3
              subPath: tournament_pb2.py
            - mountPath: /app/account_pb2_grpc.py
              name: tournament-service-cm4
              subPath: account_pb2_grpc.py
            - mountPath: /app/account_pb2.py
              name: tournament-service-cm5
              subPath: account_pb2.py
          workingDir: /app
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: requirements.txt
                path: requirements.txt
            name: tournament-service-cm0
          name: tournament-service-cm0
        - configMap:
            items:
              - key: tournament_server.py
                path: tournament_server.py
            name: tournament-service-cm1
          name: tournament-service-cm1
        - configMap:
            items:
              - key: tournament_pb2_grpc.py
                path: tournament_pb2_grpc.py
            name: tournament-service-cm2
          name: tournament-service-cm2
        - configMap:
            items:
              - key: tournament_pb2.py
                path: tournament_pb2.py
            name: tournament-service-cm3
          name: tournament-service-cm3
        - configMap:
            items:
              - key: account_pb2_grpc.py
                path: account_pb2_grpc.py
            name: tournament-service-cm4
          name: tournament-service-cm4
        - configMap:
            items:
              - key: account_pb2.py
                path: account_pb2.py
            name: tournament-service-cm5
          name: tournament-service-cm5
