apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: tournament-service
  name: tournament-service
spec:
  ports:
    - name: "50053"
      port: 50053
      targetPort: 50053
  selector:
    io.kompose.service: tournament-service
