# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tournament.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tournament.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import account_pb2 as account__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tournament.proto\x12\ntournament\x1a\raccount.proto\"k\n\nTournament\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63reator\x18\x03 \x01(\t\x12\r\n\x05prize\x18\x04 \x01(\x05\x12!\n\x07players\x18\x05 \x03(\x0b\x32\x10.account.Account\"\x07\n\x05\x45mpty2\x91\x02\n\x11TournamentService\x12=\n\x10\x43reateTournament\x12\x16.tournament.Tournament\x1a\x11.tournament.Empty\x12?\n\rGetTournament\x12\x16.tournament.Tournament\x1a\x16.tournament.Tournament\x12=\n\x10UpdateTournament\x12\x16.tournament.Tournament\x1a\x11.tournament.Empty\x12=\n\x10\x44\x65leteTournament\x12\x16.tournament.Tournament\x1a\x11.tournament.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tournament_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOURNAMENT']._serialized_start=47
  _globals['_TOURNAMENT']._serialized_end=154
  _globals['_EMPTY']._serialized_start=156
  _globals['_EMPTY']._serialized_end=163
  _globals['_TOURNAMENTSERVICE']._serialized_start=166
  _globals['_TOURNAMENTSERVICE']._serialized_end=439
# @@protoc_insertion_point(module_scope)
